# Generated by Django 2.0.1 on 2018-01-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20171229_1056'),
        ('catalog', '0021_auto_20170504_1512'),
    ]

    operations = [
    ]
