# Generated by Django 2.0.5 on 2018-05-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_merge_20180115_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
